### ISSUE TITLE
Convert network documentation, namespace, etc. to Roxygen.

### ISSUE THREAD

**Issue by krivit** [statnet/network#11]
I think `network` is the only package that hasn't been converted yet, and it would simplify maintenance somewhat.

**Comment by chad-klumb** [comment]
Currently `network` exports several S3 methods using `export` in the `NAMESPACE` file.  AFAIK `roxygen` will always use `S3method` (even if you use `@export` in the roxygen comment), which would be a problem if people were calling these methods directly.  Is there a good way around this issue?

**Comment by skyebend** [comment]
I'm not sure if there is a good way around or not, but very much agree with your intuition that we need to be careful about tweaking the namespace as we recently broke some things non-obviously by making into S3methods which altered function dispatch in depending packages. I think to do this we need a good procedure for testing impacts on depending packages

**Comment by krivit** [comment]
@chad-klumb , if you write `@export method.generic`, it'll both declare the method and export the function.

I've played around with automatic deprecation warnings (See the utilities in `statnet.common`.), but with limited success.

**Comment by chad-klumb** [comment]
Thanks, I wasn't familiar with that usage.
