### ISSUE TITLE
does/should mixingmatrix work for bipartite networks?

### ISSUE THREAD

**Issue by chad-klumb** [statnet/network#13]
when the number of levels in the first bipartition is not the same as the number of levels in the second bipartition?

e.g.

```
require(network)
m <- matrix(round(runif(4000)), 40, 100)
x <- network(m)
x %v% "race" <- c(rep("A", 20), rep("B", 20), rep("A", 30), rep("B", 30), rep("C", 40))
mixingmatrix(x, "race")
```

produces

```
Error in table(From, To) : all arguments must have the same length
```

**Comment by sgoodreau** [comment]
Hmmm, I would think that it should work.  Then again, I think we (meaning the HIV modelers among us) tend to use bipartite networks in ways that differ from the original philosophy behind their intended use.  I.e. for use it's not uncommon for the two bipartitions to share the same or overlapping set of attributes, while in their original conceptualization the two bipartitions would generally be so structurally different that they wouldn't have the same attributes. Which may open up a broader conversation:  should there be a mechanism for each bipartition to have different sets of attributes (e.g. one represents people and has attributes age and race, the other represents venues and has size and neighborhood). Presumably one can do a version of this with NAs, but I mean a more fundamental structural approach. I beleive this does not currently exist, right? Not sure this is of much use on the epi modeling side per se as we move away from formally bipartitie networks, but I did want to throw it out there.

Either way, though, conditional on the two bipartitions sharing an attribute, then I would think mixingmatrix should work for them (and it shouldn't be too hard to fix it so they do).

**Comment by chad-klumb** [comment]
Are we sure this is the new behavior we want?  AFAIK bipartite networks are regarded as having mixing matrices with only the b1 levels as rows and only the b2 levels as columns, while with current `master` e.g. this script (using `ergm` to add the edges because I'm lazy)

```
require(ergm)
nw <- network.initialize(100,bip=30,dir=F)
nw <- san(nw ~ edges, target.stats=200)
nw %v% "attr" <- c(rep(c("A","B"), length.out=30), rep(c("X","Y","Z"), length.out=70))
mixingmatrix(nw, "attr")
```

now produces

```
> mixingmatrix(nw, "attr")
       B2
B1      A B  X  Y  Z Total
  A     0 0 32 30 36    98
  B     0 0 31 33 38   102
  X     0 0  0  0  0     0
  Y     0 0  0  0  0     0
  Z     0 0  0  0  0     0
  Total 0 0 63 63 74   200
```

**Comment by mbojan** [comment]
I think this is a nice example of a somewhat broader feature of the design of network objects -- the data model is designed for unimodal (hyper)graphs because the "namespace" for vertex attributes is common to all nodes. The bipartite network objects are essentially single mode graphs, so to speak, because we can't have mode-specific attributes, i.e. defined only for one of the modes.
Incidentally, it is a similar problem with egonetworks if one considers egos and alters as separate modes and the same feature is measured differently for egos and alters.

Perhaps a solution is to have `mixingmatrix()` to construct rowset and column set separately for each mode? In Chads example only A and B will be in rows as no other values are observed in B1 and only X, Y, and Z in columns as only those are observed in B2? We can't take advantage of `factor()`s `level`s in this case as the set of levels is common to both modes (again, bipartite, but unimodal).

**Comment by mbojan** [comment]
Alternatively there could be a "method" bipartite networks (there is no S3 class for bipartite networks) that expects two nodal attributes, i.e. `mixingmatrix(bipnet, b1attr, b2attr)` assuming that in the data the convention is adopted to store vertex attributes in a mode-specific manner: separate attributes with `NA`s for nodes in the other mode...

**Comment by chad-klumb** [comment]
As an aside, I did write a `mixingmatrix.networkLite` earlier that I think fixes the problem in the OP of this post.  You can find it here:

https://github.com/statnet/tergmLite-private/blob/7f68972deea2931b7f3ef31d35006cf6b9d8c230/R/util.R#L173-L206

It appears to be working as intended with all three network types.  If we remove the dependence on `ergm_get_vattr` I think it could be used for `network`s too (although personally I like the ability to transform without having to set a separate attribute, and it's really more of a `network`-level thing than an `ergm`-level thing IMO).

Example usage:

```
require(ergm)
require(tergmLite)

## undirected ##
nw <- as.networkLite(network.initialize(10,directed=FALSE))
nw %v% "attr" <- c("A","B","A","A","C","C","C","D","D","E")
nw <- san(nw ~ edges, target.stats = 45)
mixingmatrix(nw, "attr")

## directed ##
nw <- as.networkLite(network.initialize(10,directed=TRUE))
nw %v% "attr" <- c("A","B","A","A","C","C","C","D","D","E")
nw <- san(nw ~ edges, target.stats = 90)
mixingmatrix(nw, "attr")

## bipartite ##
nw <- as.networkLite(network.initialize(10,directed=FALSE,bipartite=4))
nw %v% "attr" <- c("A","B","A","A","C","C","C","D","D","E")
nw <- san(nw ~ edges, target.stats = 24)
mixingmatrix(nw, "attr")
```

and results:

```
> require(ergm)
> require(tergmLite)
> 
> ## undirected ##
> nw <- as.networkLite(network.initialize(10,directed=FALSE))
> nw %v% "attr" <- c("A","B","A","A","C","C","C","D","D","E")
> nw <- san(nw ~ edges, target.stats = 45)
> mixingmatrix(nw, "attr")
  A B C D E
A 3 3 9 6 3
B 3 0 3 2 1
C 9 3 3 6 3
D 6 2 6 1 2
E 3 1 3 2 0
> 
> ## directed ##
> nw <- as.networkLite(network.initialize(10,directed=TRUE))
> nw %v% "attr" <- c("A","B","A","A","C","C","C","D","D","E")
> nw <- san(nw ~ edges, target.stats = 90)
> mixingmatrix(nw, "attr")
  A B C D E
A 6 3 9 6 3
B 3 0 3 2 1
C 9 3 6 6 3
D 6 2 6 2 2
E 3 1 3 2 0
> 
> ## bipartite ##
> nw <- as.networkLite(network.initialize(10,directed=FALSE,bipartite=4))
> nw %v% "attr" <- c("A","B","A","A","C","C","C","D","D","E")
> nw <- san(nw ~ edges, target.stats = 24)
> mixingmatrix(nw, "attr")
  C D E
A 9 6 3
B 3 2 1
```

This is the install stack:

```
remotes::install_github(c("statnet/rle@master", 
                          "statnet/statnet.common@master", 
                          "statnet/network@master", 
                          "statnet/networkDynamic@master", 
                          "statnet/ergm-private@dev", 
                          "statnet/ergm.multi-private@dev", 
                          "statnet/tergm-private@dev", 
                          "statnet/tergmLite-private@dev"), force=TRUE, dependencies=FALSE)
```

**Comment by krivit** [comment]
I've merged @mbojan 's PR around `mixingmatrix()` documentation, but I had excised the change to the level calculation, since it rebroke the bipartite code.

I think I have a solution that will please everyone: `as.matrix.network.adjacency()` has an `expand.bipartite=` argument that, if `TRUE`, returns a square matrix. It makes perfect sense to add this argument to the `mixingmatrix()` family.

**Comment by krivit** [comment]
Now,
```r
require(network)
m <- matrix(round(runif(4000)), 40, 100)
x <- network(m)
x %v% "race" <- c(rep("A", 20), rep("B", 20), rep("A", 30), rep("B", 30), rep("C", 40))
mixingmatrix(x, "race")
mixingmatrix(x, "race", expand.bipartite=TRUE)
```
prints the following:
```
> mixingmatrix(x, "race")
      B2
B1        A   B   C Total
  A     300 302 412  1014
  B     287 316 419  1022
  Total 587 618 831  2036
> mixingmatrix(x, "race", expand.bipartite=TRUE)
       B2
B1        A   B   C Total
  A     300 302 412  1014
  B     287 316 419  1022
  C       0   0   0     0
  Total 587 618 831  2036
```
