### ISSUE TITLE
In the speed tests, calibrate against machine speed to allow running in a virtual machine.

### ISSUE THREAD

**Issue by krivit** [statnet/network#18]
`R CMD check --use-valgrind` on the package fails for `network` because `tests/speedTests.R` uses specific numbers for time limits on its tasks. This means that running inside a virtual machine like Valgrind, which slows down the execution, can trigger false positives.

**Comment by martinamorris** [comment]
This really belongs [here](https://github.com/statnet/network/issues/15) so I'm going to transfer it.
