### ISSUE TITLE
Loading package changes behaviour of summary.data.frame() for character variables

### ISSUE THREAD

**Issue by famuvie** [statnet/network#22]
Dear all,

Seems like loading `network` changes the output of `summary()` for any data.frame with variables of class `character`. See MRE below.

I find this behaviour rather annoying. Specially for large data frames. Are you aware of this? 

``` r
td <- data.frame(
  lettres = letters[1:10],
  values = 1:10,
  stringsAsFactors = FALSE
)

summary(td)
#>    lettres              values     
#>  Length:10          Min.   : 1.00  
#>  Class :character   1st Qu.: 3.25  
#>  Mode  :character   Median : 5.50  
#>                     Mean   : 5.50  
#>                     3rd Qu.: 7.75  
#>                     Max.   :10.00
library(network)
#> network: Classes for Relational Data
#> Version 1.16.0 created on 2019-11-30.
#> copyright (c) 2005, Carter T. Butts, University of California-Irvine
#>                     Mark S. Handcock, University of California -- Los Angeles
#>                     David R. Hunter, Penn State University
#>                     Martina Morris, University of Washington
#>                     Skye Bender-deMoll, University of Washington
#>  For citation information, type citation("network").
#>  Type help("network-package") to get started.
summary(td)
#>  lettres      values     
#>  NULL:a   Min.   : 1.00  
#>  NULL:b   1st Qu.: 3.25  
#>  NULL:c   Median : 5.50  
#>  NULL:d   Mean   : 5.50  
#>  NULL:e   3rd Qu.: 7.75  
#>  NULL:f   Max.   :10.00  
#>  NULL:g                  
#>  NULL:h                  
#>  NULL:i                  
#>  NULL:j
```

I guess the responsible is the method `summary.character()` that is defined in the package.

<sup>Created on 2020-03-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krivit** [comment]
@CarterButts , it looks like it *is* breaking `summary`: instead of printing the most frequent characters, it prints that weirdness. I don't think that much is lost by just removing the method from the package. (It shouldn't break any code, since it'll just fall back to `summary.default()`.)

**Comment by mbojan** [comment]
@CarterButts @krivit they are used only internally, right? That's what I see in the code and what the comment says. I just did a quick experiment and simply not exporting `summary.character()` and `print.summary.character()` resolves the issue. I have a PR ready.
