### ISSUE TITLE
Mixing matrices and NAs on attributes

### ISSUE THREAD

**Issue by mbojan** [statnet/network#42]
Currently `mixingmatrix()` ignores ties adjacent to nodes that have `NA` on the attribute, e.g.:

```r
library(network)
data(emon)
emon$MtSi %v% "Formalization"   # some NAs
#>  [1]  1 NA  1  1  1  1  2  2 NA  1  1  1 NA
mixingmatrix(emon$MtSi, "Formalization")
#>        To
#> From     1 2 Total
#>   1     19 4    23
#>   2      4 0     4
#>   Total 23 4    27
```

which suggests there are 27 ties while in fact there are 33. The "true" mixing matrix is:

```
      To
From    1  2 <NA>
  1    19  4    4
  2     4  0    1
  <NA>  1  0    0
```

There are 6 ties adjacent to nodes with `NA`s on "Formalization".

Possible solution:
- The `table()` call within `mixingmatrix()` should use `useNA = "ifany"`
- Pass `...` to `table()` so that the user has full control.

**Comment by martinamorris** [comment]
Yikes.  I'd vote for implementing both solutions above.  The default should not be to remove them silently, and important to display the NAs by default so the user is alerted.

**Comment by krivit** [comment]
I agree. Generally, making `mixingmatrix()` consistent with `table()` as practical seems to me like a good idea.

**Comment by mbojan** [comment]
Passing to `table()` anything else apart from `exclude=NULL` or `useNA="always"` or `useNA="no"` (as is currently effectively) causes an avalanche of Yenga bricks for undirected networks with `NA`s on the attribute. The reason is that the MM can no longer be assumed symmetric. 

Out of

1. Keep the default as is, but pass `...` to `table()` adding to the documentation of `...` that the user should use `exclude=` or `useNA=` to check if there are `NA`s on the attribute. This is basically as `table()` works for ages now.
2. Enforce `exclude=NULL` so there will be always rows and columns for `NA` values even if not present

I'm leaning towards (1). What are your opinions @CarterButts @krivit @martinamorris ?

**Comment by mbojan** [comment]
Passing `...` to `table()`. Can't use `"ifany"` for undirected networks:

```r
net <- network.initialize(2, directed=FALSE)
net %v% "a" <- c(1,NA)
net[1,2] <- 1
mixingmatrix(net, "a", useNA = "ifany")
## Error in tabu + t(tabu) : non-conformable arrays
```

**Comment by krivit** [comment]
@mbojan, I think that we can solve the problem with the following logic: If `useNA!="no"` and `anyNA(nodecov)` and `!is.bipartite(nw)`, then pass `useNA="always"` to `table()`. Otherwise, propagate `useNA` as passed.

Does that work?

**Comment by mbojan** [comment]
Yes, I think so. I was considering showing both `NA` rows and columns if and only if (1) there are `NA`s and (2) `useNA != "no"` seems to be identical to your idea. (apart from bipartite nets).

**Comment by krivit** [comment]
@mbojan , were these commits ever merged into `master`?

**Comment by mbojan** [comment]
@krivit , I ended-up exposing `useNA` and internally set it to either "no" or "always" depending whether there are `NA`s on the attribute. Additionally, any "hacking" by using `exclude` to override `useNA` is ignored with a warning. I think this is an acceptable compromise between, on the one hand, showing NAs when present and, on the other hand, (re)implementing the whole logic of `table()` with the twist of having always square matrix as the result.

If CI passes I think we can merge this.

**Comment by mbojan** [comment]
Perhaps it actually make more sense to finish-up #32 first.
