### ISSUE TITLE
mixingmatrix() sometimes return integer, sometimes numeric

### ISSUE THREAD

**Issue by mbojan** [statnet/network#44]
Should we enforce always integer? These are always counts after all.

**Comment by krivit** [comment]
@mbojan , how about now?

**Comment by mbojan** [comment]
Not yet, this one trips:

```r
net <- network.initialize(4, directed=FALSE)
net[1,2] <- net[1,3] <- 1
net %v% "a" <- c(1,1, 2,2)
is.integer(mixingmatrix(net, "a")$matrix)
## FALSE
```

**Comment by mbojan** [comment]
I'll commit the tests first as there are some more cases I think

**Comment by mbojan** [comment]
Done

**Comment by mbojan** [comment]
This is failing now:

https://github.com/statnet/network/blob/5a1c557fd01f4eb4971f134383c6d452a2731645/tests/testthat/test-mixingmatrix.R#L50
