### ISSUE TITLE
querying missing edge attributes should return NA vector, not NULL

### ISSUE THREAD

**Issue by mkoohafkan** [statnet/network#5]
When querying a vertex attribute that does not exist in the graph, a vector of NA values is returned with the same length as the number of vertices in the graph. However, querying a missing edge attribute returns NULL. It would be nice if `%v%` and `%e%` behaved consistently, i.e. if `%e%` returned a vector of NA values with length equal to the number of edges. Example below: 

```
set.seed(5)
m <- matrix(rbinom(25,1,.4),5,5)
diag(m) <- 0
g <- network(m, directed = TRUE)

g %v% "foo"
## [1] NA NA NA NA NA

g %e% "foo"
## NULL
```

**Comment by krivit** [comment]
@CarterButts , what do you think?

**Comment by skyebend** [comment]
I think that tho this may have been a good idea in the first place, this would be a big change that would likely break a lot of depending code.  

 Can you get what you need via get.edge.attribute with the null.na arg?
```
> get.edge.attribute(g,'foo',null.na = TRUE)
[1] NA NA NA NA NA NA NA NA NA
```

**Comment by mkoohafkan** [comment]
Nice, `null.na` argument will work just fine.

**Comment by krivit** [comment]
It might make more sense to return `NULL` by default in both cases, analogously to `data.frame`. I wonder if that would break anything.

**Comment by skyebend** [comment]
I think there may have been good-ish reasons for this because the complexities of working around deleted edges, can't remember exactly, but I think that is why the null.na flag exists.  And I'm pretty sure there is code depending on current behavior that would break.

**Comment by CarterButts** [comment]
Yes, there are several of these sorts of things that stem from the fact that the original version of network wasn't backended, and edges could not be removed once deleted; for backward compatibility, this was kept once the backended version appeared.  Some Fine Day (TM) the mel storage system should be redone to get rid of this, but this requires a deep change to the core code and would break everything not using vanilla access methods.  So, for now, I think it is as it is....
