### ISSUE TITLE
Get rid of TravisCI?

### ISSUE THREAD

**Issue by mbojan** [statnet/network#51]
GH actions suffice, don't they?

**Comment by krivit** [comment]
I think so. Ditto Appveyor. We never did get it to work quite right, and I had hacked the `R CMD check` script to create Windows binaries much more accessibly than Appveyor's.

**Comment by mbojan** [comment]
Config files removed. I believe some one with appropriate credentials needs login to TravisCI/AppVeyor and unregsiter this repo.

**Comment by krivit** [comment]
Done.
