### ISSUE TITLE
Data objects in a separate package 'statnet.data'

### ISSUE THREAD

**Issue by mbojan** [statnet/network#54]
While writing tests for `mixingmatrix()` I was limited to the datasets within `network` and could not use, say, ones from `ergm` as `ergm` depends `network` not the vice versa. 

Perhaps it would make sense to have a separate pure data package? 

That would, facilitate reusing different datasets in different packages in tests and examples

**Comment by martinamorris** [comment]
I like this idea, but I wonder whether we need self contained packages for testing.  How does the tidyverse solve this problem?

**Comment by krivit** [comment]
If they were only for tests, we could use `Suggest`, but since we want them in examples and a seamless user experience, we can `Import` it and then use, e.g., `data(sampson, package="statnet.data")` in our examples.

**Comment by CarterButts** [comment]
Long ago, we had an early stab at a statnet data package (though it never became clean/documented enough for general use).  Separately, Zack Almquist put together a package with a bunch of Lin Freeman's old examples, which was in somewhat better shape (though IIRC still not 100% ready for mass dissemination).  If it would be helpful, I can put the versions of both that I have on a private repository, and folks could take a look.....

**Comment by handcock** [comment]
I also have one that I use for class that likely has a lot of overlap with Carter and Zack's. It may be possible to merge them.

**Comment by CarterButts** [comment]
It definitely seems like something that is worth looking into, at least!  I will put the packages I have up backstage, and we can figure out what makes sense - if nothing else, this will ensure that everyone on the team has access to them.

**Comment by mbojan** [comment]
Thank you all! I have already set up a skeleton at https://github.com/statnet/statnet.data and will start with copying the datasets and documentation from the published Statnet packages (copied `emon` from `network` by now). Once they are copied we can start removing them from other packages, adding `statnet.data` to `Imports:` and adjust tests or examples accordingly.

> If they were only for tests, we could use `Suggest`, but since we want them in examples and a seamless user experience, we can `Import` it and then use, e.g., `data(sampson, package="statnet.data")` in our examples.

Yep. Since the package will not contain any code I want to see if it will be `R CMD check`-kosher to:
- `statnet.data` not have any dependency whatsoever (even though I use some R code and packages in generating documentation)
- other statnet packages will `Imports` it

I think we can definitely extended with other datasets as far as CRAN will accept the package weight.

**Comment by skyebend** [comment]
> statnet.data not have any dependency whatsoever (even though I use some R code and packages in generating documentation)

Are some of the datsets network objects tho? Seems like it would work if they are raw data.frames

**Comment by krivit** [comment]
The old SVN repositories had two statnet dataset packages.

**Comment by mbojan** [comment]
> 
> 
> > statnet.data not have any dependency whatsoever (even though I use some R code and packages in generating documentation)
> 
> Are some of the datsets network objects tho? Seems like it would work if they are raw data.frames

Almost all of them are. It should work although doing anything with them (including `print()`ing) will require loading (or attaching `network`). Perhaps I'll add `Suggests: network` for the sake of in-documentation examples.

**Comment by CarterButts** [comment]
FYI, I created private repositories for networkdata and netdata (the old packages).   **_Do not assume that the data is in good shape._**  Most of it is, I think, but IIRC there were some glitches that never were fixed - so this is not a simple copypasta situation.  (Maybe copypasta but verify.)  Also, note that the AddHealth public network objects are in one of the packages.  My understanding is that this data (which is non-private, non-identifying, and has been floating around forever - Lin used to have it on his web page) is kosher to disseminate.  However, stuff like that should be verified before anyone tries to put anything in the public sphere.

**Comment by CarterButts** [comment]
@mbojan as far as format, I vote for putting everything in network object form (I believe that all of them already are), and use that as the sole dependency.  (1) that's what those objects are intended for, and (2) we can always export to other formats for testing purposes.  Also, (3) many of the data sets have rich metadata, and network objects are designed to handle that in a natural and general way (which is not true of other formats).

**Comment by mbojan** [comment]
> 
> 
> @mbojan as far as format, I vote for putting everything in network object form (I believe that all of them already are), and use that as the sole dependency. (1) that's what those objects are intended for, and (2) we can always export to other formats for testing purposes. Also, (3) many of the data sets have rich metadata, and network objects are designed to handle that in a natural and general way (which is not true of other formats).

I think so too. I believe the only non-network data is `flo` adjacency matrix in "network" package otherwise available as a `network` object in "ergm".

**Comment by mbojan** [comment]
> FYI, I created private repositories for networkdata and netdata (the old packages). **_Do not assume that the data is in good shape._** Most of it is, I think, but IIRC there were some glitches that never were fixed - so this is not a simple copypasta situation. (Maybe copypasta but verify.) Also, note that the AddHealth public network objects are in one of the packages. My understanding is that this data (which is non-private, non-identifying, and has been floating around forever - Lin used to have it on his web page) is kosher to disseminate. However, stuff like that should be verified before anyone tries to put anything in the public sphere.

@CarterButts I can't see them. Did you create the repos in the Statnet namespace?

**Comment by CarterButts** [comment]
@mbojan Yes, they should be there.  Let me check....

**Comment by mbojan** [comment]
Thanks @CarterButts , got the invites.

Let's move further discussion to https://github.com/statnet/statnet.data/issues, closing this now.
