### ISSUE TITLE
Extended read.paj() tests are failing.

### ISSUE THREAD

**Issue by krivit** [statnet/network#56]
That is, if run with `ENABLE_statnet_TESTS=yes`, something goes wrong. @skyebend it looks like you wrote them, with @mbojan and @knapply making some changes. Can someone please take a look?

**Comment by mbojan** [comment]
I further propose to

1. Wrap the tests with `test_that()`
2. ... which will also allow to use `skip_on_cran()` and get rid of the envvar mechanic.

**Comment by krivit** [comment]
@mbojan , all great ideas. At the moment, I just want the tests to stop failing.
