### ISSUE TITLE
Release network 1.17

### ISSUE THREAD

**Issue by krivit** [statnet/network#58]
# Checklist before submitting to CRAN

Note that the final submission must be done by @CarterButts.

## Directions for use

1. Create an appropriately named issue (e.g., "Release package version *version*.").
1. Copy-paste this file into the issue text to provide the checklist functionality.
1. **After a commit directly pursuant to a checkbox item**, uncheck all checkboxes below it.
1. **After any other commit to `master` branch**, uncheck all boxes from the "`master` branch" section down.
1. **After any other commit to `*release*` branch**, uncheck boxes from the "Release branch" section down.
1. Close the issue after all boxes are checked.

## `master` branch

* [x] `DESCRIPTION`: Package's CRAN dependencies require a recent CRAN version.
* [x] `DESCRIPTION`: Package's dependencies that are a part of R core (`base`, `datasets`, `grDevices`, `methods`, `splines`, `stats4`, `tools`, `utils`, `compiler`, `graphics`, `grid`, `parallel`, `stats`, `  tcltk`, `translations`) do *not* specify a version.
* [x] `DESCRIPTION`: Package's dependencies that are usually shipped with R (`KernSmooth`, `Matrix`, `MASS`, `class`, `nnet`, `spatial`, `boot`, `cluster`, `codetools`, `foreign`, `lattice`, `mgcv`, `nlme`, `rpart`, `survival`) do *not* specify a version unless necessary.
* [x] All tickets associated with the release's milestone have been resolved.
* [ ] The stubs file in `inst/include/` is up to date if needed.
* [x] Roxygen has been run on the package since last commit to code, documentation, or `DESCRIPTION`.
* [ ] Relevant tutorials run satisfactorily.
* [x] `inst/NEWS.Rd`: file is up to date: none of the commits since the last commit to explicitly mention updating the `NEWS` file are newsworthy.
* [ ] `LICENSE`: license refers to the correct package.
* [ ] `LICENSE`: affiliations are up to date.
* [ ] `LICENSE`: copyright year range is correct.
* [ ] All files that should have them have copyright headers. Generally, it never hurts to rerun `addcopyheaders` to ensure this.
* [x] `R CMD check` passes with `ENABLE_statnet_TESTS=yes` environment variable *and* `--run-donttest`.
* [ ] `rchk` static code analysis passes.
* [x] Reverse dependency checks pass unless breakage known.

## Release branch (`v1.17`)

* [x] Release branch has had the latest `master` merged into it. (`git checkout *release*; git merge master`)
* [x] `DESCRIPTION`: There are no `Remotes:` directives (unless releasing simultaneously).
* [ ] `R-CMD-check.yaml`: `rcmdcheck()` is called with `error_on = "warning"`.
* [x] `DESCRIPTION`: Release branch's version number does not have commit number attached to it.
* [ ] `DESCRIPTION`: Date is today.
* [x] `CITATION`: `update_CITATION` has been run after installing all the mentioned packages from the release branch.
* [x] All files in the release branch have been committed and pushed to GitHub.
* [x] `*pkg*.tar.gz`: the candidate submission file is from the latest version of the release branch.
* [x] `*pkg*.tar.gz`: `R CMD check` passes with `ENABLE_statnet_TESTS=yes` environment variable *and* `--run-donttest`.
* [x] `*pkg*.tar.gz`: `R CMD check` passes with `--as-cran` option without `WARNING`s.
* [x] `*pkg*.tar.gz`: `R CMD check` passes Win-Builder (https://win-builder.r-project.org).
* [x] `*pkg*.tar.gz`: `R CMD check` passes on the previous stable release (unless there is a good reason to require the latest R).

## After release

* [x] Release branch corresponding to the package on CRAN has been tagged with the exact CRAN version and pushed to GitHub.

**Comment by krivit** [comment]
I have created a release branch `v1.17`, in which I have eliminated dependence on `statnet.common` 4.5: it now works with the CRAN version. I had informed the reverse-dependency developers of the changes and the breakages on 20 May.

As far as I know, there is nothing blocking the release of `network` now. Given all the other packages in the pipeline, the sooner we release, the better.

Some of the items on this checklist are not applicable, and others I can't complete because `network` uses "nonstandard" `LICENSE` file and file headers, I am not very familiar with its C API or tutorials, and I don't know what should be done with https://github.com/statnet/network/issues/59 .

@CarterButts, @mbojan, @chad-klumb , can I ask you to please it the rest of the way?

**Comment by CarterButts** [comment]
v1.17 is now passing checks on Rhub and all three versions of winbuilder, plus my at-home checks.  So I think it's good to go.  Unless I hear immediate objections, I will begin the transfer.  Thanks @krivit and @martinamorris for your help w/pre-checks!

**Comment by CarterButts** [comment]
Package has been pushed.  Will update and close when/if it passes muster on their end...

**Comment by CarterButts** [comment]
Argh.  JSS has moved from http to https, so it failed because the URLs weren't of the correct type.  _And, of course, because it is CRAN, **no other testing utilities but their own internal one flagged this as an issue.**_  After all these years, this remains a constant: they always apply super secret squirrel tests on packages that are never covered in their other testing utilities (including WinBuilder and friends).  Why do they make such work for themselves?  Like wavefunction collapse, it is a deep and impenetrable mystery.

It does appear, in any event, that one's external measurement of a package status and that of CRAN do not diagonalize in the same basis.

Fixed the issues and am trying again.....

**Comment by CarterButts** [comment]
OK, they may have taken it.  Not yet clear.  Will check tomorrow, and update things accordingly.

**Comment by martinamorris** [comment]
lol, super secret squirrels.  fingers crossed.

**Comment by CarterButts** [comment]
The latest hurdle is the revdep issue.  Have explained it.  Hopefully, they will weigh us lightly on the scales of Ma'at.

**Comment by drh20drh20** [comment]
Scales of Ma'at... Now there's a reference I had to look up.  

Indeed, may release 1.17 be judged lighter than the proverbial feather by the priests of CRAN!

**Comment by CarterButts** [comment]
The package has passed the final acceptance phase.  The package will propagate to CRAN in a few hours.  You may start your landing.
