### ISSUE TITLE
mixingmatrix function -- no man page entry

### ISSUE THREAD

**Issue by martinamorris** [statnet/network#6]
is there a reason?

**Comment by krivit** [comment]
I think it's that it was initially an internal function, used to print the mixing matrices in `summary.network()`.

**Comment by martinamorris** [comment]
> I think it's that it was initially an internal function, used to print the mixing matrices in summary.network().

perhaps, but it's an important end user utility, for EDA and diagnostics. 
i thought i remembered a line that warned the margins were not correct for 
undirected net mixing matrices, from a man page entry for this function. 
am i wrong about that?

**Comment by krivit** [comment]
I recall something similar. But, yes, someone should write it.

**Comment by mbojan** [comment]
There were a couple of functions with code `R/misc.R` but separate help pages. I took the freedom to put the code of all the functions apart from those documented in the topic `network-internal` in their own files. This includes `mixingmatrix()` which will have now its own man page.

**Comment by mbojan** [comment]
PR incoming, but perhaps it will make sense to merge the open ones first? @CarterButts @krivit @martinamorris ? I'm not sure who is in charge of the suitcase with the red "merge!" button 😃

**Comment by krivit** [comment]
Thanks, @mbojan .

**Comment by krivit** [comment]
@mbojan , just checking in---are you planning to put together a PR any time soon?

**Comment by mbojan** [comment]
Its ready at https://github.com/mbojan/network/tree/i6-mixingmatrix, let me just make sure I did not miss anything...

**Comment by mbojan** [comment]
I'll reopen the PR after the open ones are merged.
