### ISSUE TITLE
Implement xor() operation for networks.

### ISSUE THREAD

**Issue by krivit** [statnet/network#60]
All the other logical operations are supported.

**Comment by krivit** [comment]
At the moment, the default `xor(x,y)` is implemented as `(x | y) & !(x & y)`, but this involves constructing very dense temporary network.

We would be better off doing it either directly or as `(x - y) | (y - x)`.

**Comment by CarterButts** [comment]
Direct would be faster, but it depends on how performance-sensitive your case is.  Do you have a sense of how big a network you want to support at the moment?  Also, is this urgent enough to block 1.17 while I implement something, or is this a wishlist item?  A quick-and-dirty version could be added now; I would have to re-run some tests, but it is unlikely to break much.

**Comment by krivit** [comment]
I'd like it to make it into 1.17, but it's not at all critical. I think the performance of the `(x - y) | (y - x)` implementation should be adequate, since at least it doesn't negate a sparse network. I am working on a PR now and will open it in the next 10 minutes.

**Comment by krivit** [comment]
Cancel that. `xor` is not generic. Do you want me to take a quick look at the package before pushing it?

**Comment by krivit** [comment]
We may want to *make* it generic and reimplement, given the inefficiency, but that can wait.

**Comment by krivit** [comment]
I had saved my implementation in a branch, but I don't think we should release it without further discussion.

**Comment by krivit** [comment]
So, for now, let 1.17 fly!
