### ISSUE TITLE
bug(s) in as.edgelist

### ISSUE THREAD

**Issue by chad-klumb** [statnet/network#70]
when using a character edge attribute, e.g.

```
require(network)
nw <- network.initialize(10, dir = F)
nw[1,5] <- 1
nw[1,10] <- 1
nw %e% "attr" <- c("a","b")
as.edgelist(nw)
as.edgelist(nw, attrname = "attr")
```

produces

```
> as.edgelist(nw)
     [,1] [,2]
[1,]    1    5
[2,]    1   10
attr(,"n")
[1] 10
attr(,"vnames")
 [1]  1  2  3  4  5  6  7  8  9 10
attr(,"directed")
[1] FALSE
attr(,"bipartite")
[1] FALSE
attr(,"loops")
[1] FALSE
attr(,"class")
[1] "matrix_edgelist" "edgelist"        "matrix"          "array"          
> as.edgelist(nw, attrname = "attr")
     [,1] [,2] [,3]
[1,] "1"  "10" "b" 
[2,] "1"  "5"  "a" 
attr(,"n")
[1] 10
attr(,"vnames")
 [1]  1  2  3  4  5  6  7  8  9 10
attr(,"directed")
[1] FALSE
attr(,"bipartite")
[1] FALSE
attr(,"loops")
[1] FALSE
attr(,"class")
[1] "matrix_edgelist" "edgelist"        "matrix"          "array"  
```

the second edgelist being sorted incorrectly.

Also,
```
require(network)
nw <- network.initialize(10, dir = F, bip = 4)
nw[1,5] <- 1
nw[1,10] <- 1
nw %e% "attr" <- c("a","b")
as.edgelist(nw)
as.edgelist(nw, attrname = "attr")
```

produces

```
> as.edgelist(nw)
     [,1] [,2]
[1,]    1    5
[2,]    1   10
attr(,"n")
[1] 10
attr(,"vnames")
 [1]  1  2  3  4  5  6  7  8  9 10
attr(,"directed")
[1] FALSE
attr(,"bipartite")
[1] 4
attr(,"loops")
[1] FALSE
attr(,"class")
[1] "matrix_edgelist" "edgelist"        "matrix"          "array"          
> as.edgelist(nw, attrname = "attr")
     [,1] [,2] [,3]
[1,] "1"  "5"  "a" 
attr(,"n")
[1] 10
attr(,"vnames")
 [1]  1  2  3  4  5  6  7  8  9 10
attr(,"directed")
[1] FALSE
attr(,"bipartite")
[1] 4
attr(,"loops")
[1] FALSE
attr(,"class")
[1] "matrix_edgelist" "edgelist"        "matrix"          "array"          
```

the edge `1-10` having been dropped entirely from the second edgelist.

Both issues could be due to making string comparisons instead of integer comparisons.

**Comment by krivit** [comment]
This is because `matrix` objects can only store one data type, so if the attribute is character, the node IDs get converted to character as well and get sorted alphabetically. If you want to preserve their sorting, use `output="tibble"`, since data frames can have different types of data in different columns.

Other than making `tibble` output the default, possibly breaking other code, I don't know how we can address this.

**Comment by chad-klumb** [comment]
sorting and screening can be done with tails and heads coerced to integers even if the final output is character

completely dropping edges (as in the second example) seems totally unacceptable to me

**Comment by krivit** [comment]
Fair enough. I'd recommend outputting to `tibble` whenever possible anyway.

> completely dropping edges (as in the second example) seems totally unacceptable to me

Apologies, didn't see this item.
