### ISSUE TITLE
labels for plot.network in multi-panel formats

### ISSUE THREAD

**Issue by martinamorris** [statnet/network#8]
The default `plot.network(nw, displaylabels=T)` does a pretty good job of placing the labels:
![image](https://user-images.githubusercontent.com/8194530/49255460-ee3d0380-f3e0-11e8-8eb5-e561b873de9f.png)

But when this same plot is included in a multipanel figure, the labels (for all the plots) are not usefully placed:
![image](https://user-images.githubusercontent.com/8194530/49255428-d36a8f00-f3e0-11e8-856f-49696c99e7b4.png)

I've tried playing with the `pad=` argument, but that doesn't fix the problem.  `pad=1.0` below (default is 0.2).
![image](https://user-images.githubusercontent.com/8194530/49255585-568be500-f3e1-11e8-9bc5-35699dfb2465.png)

Is this a known and/or fixable issue?

Reprex:
library(network)
data(samplk)

plot(samplk1, main = "Time 1", displaylabels = T, pad=1.0)
par(mfrow = c(2,2))
plot(samplk1, main = "Time 1", displaylabels = T, pad=1.0)
plot(samplk1, main = "Time 1", displaylabels = T, pad=1.0)
plot(samplk1, main = "Time 1", displaylabels = T, pad=1.0)
plot(samplk1, main = "Time 1", displaylabels = T, pad=1.0)

**Comment by skyebend** [comment]
Martina, is your original example from using 'zoom' on the Rstudio plot window?  (labels look quite off to me in the very first example)  I notice that labels look fine in normal rstudio window, or 'classic' R plot window, but zooming the R plot window makes them way off.  Some sort of weird interaction with the Rstudio plot device?

**Comment by martinamorris** [comment]
It was.  And just checking again I don't get the same behavior with the current versions of R/Rstudio/network.
